jwt:
  issuer: shall-we-code
  secret: shall-we-code-secret-key

server:
  port: 50000

spring:
  cloud:
    gateway:
      routes:
        - id: swc-backend
          uri: http://localhost:50200
          predicates:
            - Path=/backend/**


