server:
  port: 50000
  max-http-header-size: 40KB

jwt:
  issuer: shall-we-code
  secret: A@RUIOJHBGDF!@42321
  expireDurationDay: 7

redis:
  config:
    host: localhost
    port: 6379

## /actuator/gateway/routes 로 라우팅 정보를 볼 수 있다.
management:
  endpoints:
    web:
      exposure:
        include: gateway

spring:
  cloud:
    gateway:
      routes:
        - id: shall-we-code
          uri: http://localhost:50200
          predicates:
            - Path=/shallwecode/**
          filters:
            - RewritePath=/shallwecode/(?<path>.*),/$\{path}
            - JwtAuthentication
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "http://localhost:3000"
            allowed-methods:
              - GET
              - PUT
              - DELETE
              - POST
              - OPTIONS
              - HEAD
            allowed-headers: "*"

